//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrowdSub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class request
    {
        public request()
        {
            this.upvotes = new HashSet<upvote>();
        }
    
        public int id { get; set; }
        public int request_user_id { get; set; }
        public string request_name { get; set; }
        public string request_link { get; set; }
        public string request_type { get; set; }
        public int request_lang { get; set; }
        public Nullable<int> request_video_id { get; set; }
        public System.DateTime request_date_created { get; set; }
    
        public virtual user user { get; set; }
        public virtual video video { get; set; }
        public virtual ICollection<upvote> upvotes { get; set; }
    }
}
