//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrowdSub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subtitle_comments
    {
        public string id { get; set; }
        public int sc_user_id { get; set; }
        public int sc_sub_id { get; set; }
        public string sc_comment { get; set; }
        public System.DateTime sc_date_created { get; set; }
    
        public virtual user user { get; set; }
        public virtual subtitle subtitle { get; set; }
    }
}
