//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrowdSub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subtitle
    {
        public subtitle()
        {
            this.subtitle_comments = new HashSet<subtitle_comments>();
        }
    
        public int id { get; set; }
        public Nullable<int> subtitle_user_id { get; set; }
        public int subtitle_video_id { get; set; }
        public string subtitle_file_path { get; set; }
        public int subtitle_version_is_active { get; set; }
        public int subtitle_version { get; set; }
    
        public virtual ICollection<subtitle_comments> subtitle_comments { get; set; }
        public virtual user user { get; set; }
        public virtual video video { get; set; }
    }
}
