//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrowdSub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.subtitle_comments = new HashSet<subtitle_comments>();
            this.subtitles = new HashSet<subtitle>();
            this.upvotes = new HashSet<upvote>();
            this.videos = new HashSet<video>();
            this.requests = new HashSet<request>();
        }
    
        public int id { get; set; }
        public string user_name { get; set; }
        public int user_role { get; set; }
        public string user_password { get; set; }
        public string user_email { get; set; }
        public Nullable<System.DateTime> user_date_created { get; set; }
    
        public virtual ICollection<subtitle_comments> subtitle_comments { get; set; }
        public virtual ICollection<subtitle> subtitles { get; set; }
        public virtual ICollection<upvote> upvotes { get; set; }
        public virtual ICollection<video> videos { get; set; }
        public virtual ICollection<request> requests { get; set; }
    }
}
