//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrowdSub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class video
    {
        public video()
        {
            this.subtitles = new HashSet<subtitle>();
            this.requests = new HashSet<request>();
        }
    
        public int id { get; set; }
        public int video_created_by_user_id { get; set; }
        public string video_title { get; set; }
        public string video_type { get; set; }
        public Nullable<int> video_year_published { get; set; }
        public System.DateTime video_date_created { get; set; }
        public System.DateTime video_date_updated { get; set; }
        public string video_description { get; set; }
    
        public virtual ICollection<subtitle> subtitles { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<request> requests { get; set; }
    }
}
